version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
    volumes:
      - ./TARS:/app
