version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
    volumes:
      - ./TARS:/app
    environment:
      - NODE_ENV=production
    volumes:
      - type: volume
        source: mydata
        target: /data
volumes:
  mydata:
    name: "mydata_volume"
