apiVersion: apps/v1
kind: Deployment
metadata:
  name: tars-deployment
spec:
  replicas: 1  # Set the number of replicas for production
  selector:
    matchLabels:
      app: tars
  template:
    metadata:
      labels:
        app: tars
    spec:
      containers:
      - name: tars
        image: ghcr.io/gpsandhu23/tars:IMAGE_TAG_PLACEHOLDER  # Will be replaced in the workflow
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        envFrom:
        - secretRef:
            name: tars-secrets  # Reference to the secret containing all environment variables

---
apiVersion: v1
kind: Service
metadata:
  name: tars-service
spec:
  type: LoadBalancer  # For cloud environments, creates an external load balancer
  ports:
    - port: 443  # Expose the service on port 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: tars
