name: Deploy Infrastructure

on:
  push:
    branches:
      - main  # Restrict to main branch
    paths:
      - 'infrastructure/**'  # Only run when infrastructure code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Deploy Infrastructure
      run: |
        cd infrastructure
        chmod +x deploy.sh  # Ensure the script is executable
        ./deploy.sh
        # Consider handling specific CLI commands directly here instead of relying solely on external scripts for better error handling