name: Deploy to Production

on:
  push:
    branches:
      - main  # This workflow triggers on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/gpsandhu23/tars:${{ github.sha }} .
        docker push ghcr.io/gpsandhu23/tars:${{ github.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Assuming the same AWS credentials can deploy to both environments
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up EKS kubectl context
      run: |
        aws eks update-kubeconfig --name tars-test --region us-west-2  # The cluster name stays the same

    - name: Update Image Tag in Production Deployment File
      run: |
        sed -i 's|ghcr.io/gpsandhu23/tars:IMAGE_TAG_PLACEHOLDER|ghcr.io/gpsandhu23/tars:${{ github.sha }}|' ./deployment/deployment-prod.yml

    - name: Deploy to Production
      run: |
        kubectl apply -f ./deployment/deployment.yml
        kubectl rollout status deployment/tars-deployment