name: Deploy to EKS

on:
  push:
    branches:
      - stage  # This workflow triggers on pushes to the stage branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/gpsandhu23/tars:${{ github.sha }} .
        docker push ghcr.io/gpsandhu23/tars:${{ github.sha }}
    
    # New step to replace the image tag placeholder
    - name: Update Image Tag in Deployment File
      run: |
        sed -i 's|ghcr.io/gpsandhu23/tars:IMAGE_TAG_PLACEHOLDER|ghcr.io/gpsandhu23/tars:${{ github.sha }}|' deployment-stage.yml

    # Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment-stage.yml
        kubectl rollout status deployment/tars-deployment-stage