name: Deploy to EKS and Run Evaluations

on:
  push:
    branches:
      - stage  # This workflow triggers on pushes to the stage branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/gpsandhu23/tars:${{ github.sha }} .
          docker push ghcr.io/gpsandhu23/tars:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up EKS kubectl context
        run: |
          aws eks update-kubeconfig --name tars-test --region us-west-2

      - name: Update Image Tag in Deployment File
        run: |
          sed -i 's|ghcr.io/gpsandhu23/tars:IMAGE_TAG_PLACEHOLDER|ghcr.io/gpsandhu23/tars:${{ github.sha }}|' ./deployment/deployment-stage.yml

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./deployment/deployment-stage.yml
          kubectl rollout status deployment/tars-deployment-stage

  run-evaluations:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Ensures that this job runs after build-and-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Set the Python version as per your requirement

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Evaluation Script
        run: |
          cd TARS
          python -m evals.CI_evaluator
